pel:
  inputs:
    - path: /media/WMG/Bildverarbeitung/TN Selektivvertrag Exomdiagnostik/Dokumentation Exomdiagnostik 01.10.2020.xlsx
      tables:
        - name: Tabelle1
          mappings:
          - original_name: Kommentar
            mapped_name: Kommentar
          - original_name: Second Look
            mapped_name: Second Look
            formatter: name
          - original_name: Bearbeiter
            mapped_name: First Look
            formatter: name
          - original_name: LB Nummer
            mapped_name: LB ID
            formatter: lbid
          - original_name: SAP-Nummer
            mapped_name: SAP ID
            formatter: numeric
          - original_name: Name
            mapped_name: Lastname
            formatter: name
            required: True
          - original_name: Vorname
            mapped_name: Firstname
            formatter: name
            required: True
          - original_name: Geburtsdatum
            mapped_name: Birthdate
            formatter: date
          - original_name: Geschlecht
            mapped_name: Gender
            formatter: gender
          - original_name: Diagnose
            mapped_name: ICD10
          - original_name: Erstberatungs-Datum
            mapped_name: Datum Einschluss
            formatter: date
          - original_name: klinischer Ansprechpartner
            mapped_name: Clinician
            formatter: name
          - original_name: Zufallsbefund
            mapped_name: Zufallsbefunde
            formatter: boolean
          - original_name: Daten-Einverständnis
            mapped_name: Datenverarbeitung
            formatter: boolean
          - original_name: Foto-Einverständnis
            mapped_name: Fotoeinverständnis
            formatter: boolean
          - original_name: Gestaltmatcher-ID
            mapped_name: Gestaltmatcher-EV
            formatter: boolean
          - original_name: HPO-ID
            mapped_name: HPO Terms
          - original_name: Gen. Basisdiagnostik (Chromosomen, Array-CGH)
            mapped_name: Basisdiagnostik
            formatter: string
          - original_name: Paneldiagnostik
            mapped_name: Paneldiagnostik
            formatter: string
          - original_name: Fallkonferenz 1 Datum
            mapped_name: Datum Fallkonferenz
            formatter: date
          - original_name: Genom/Exom
            mapped_name: Falltyp
            formatter: string
          - original_name: gelöst (ja/ein/UV3)
            mapped_name: Status
            formatter: string
          - original_name: FK Befundbesprechung Datum
            mapped_name: Datum Befundkonferenz
            formatter: date
          - original_name: Datum Befund
            mapped_name: Datum Befund
            formatter: date
          - original_name: ACMG Kriterien
            mapped_name: V|1|ACMG Classification
            formatter: string
          - original_name: Hauptbefund (Gen)
            mapped_name: V|1|Genename
            formatter: string
          - original_name: Mutationsformel
            mapped_name: V|1|Mutation
            formatter: string
          - original_name: Status (het/hom, comp-het, de novo)
            mapped_name: V|1|Zygosity
            formatter: string
          - original_name: Zufallsbefund (Gen)
            mapped_name: V|2|Genename
            formatter: string
          - original_name: Mutationsformel Zufallsbefund
            mapped_name: V|2|Mutation
            formatter: string
          - original_name: Forschungsrelevanterbefund
            mapped_name: V|3|Mutation
            formatter: string
          - original_name: TE an Frau Otto geschickt
            mapped_name: TE an Frau Otto
            formatter: string
outputs:
  - path: tnamse.json
    output_type: json
    filter:
      type: none
    mappings:
    - original_name: Kommentar
    - original_name: Second Look
      formatter: name
    - original_name: First Look
      formatter: name
    - original_name: LB ID
      formatter: lbid
    - original_name: SAP ID
      formatter: numeric
    - original_name: Lastname
      formatter: name
    - original_name: Firstname
      formatter: name
    - original_name: Birthdate
      formatter: date
    - original_name: Gender
      formatter: gender
    - original_name: ICD10
    - original_name: Datum Einschluss
      formatter: date
    - original_name: Clinician
      formatter: name
    - original_name: Zufallsbefunde
      formatter: boolean
    - original_name: Datenverarbeitung
      formatter: boolean
    - original_name: Fotoeinverständnis
      formatter: boolean
    - original_name: Gestaltmatcher-EV
      formatter: boolean
    - original_name: HPO Terms
    - original_name: Basisdiagnostik
      formatter: string
    - original_name: Paneldiagnostik
      formatter: string
    - original_name: Datum Fallkonferenz
      formatter: date
    - original_name: Falltyp
      formatter: string
    - original_name: Status
      formatter: string
    - original_name: Datum Befundkonferenz
      formatter: date
    - original_name: Datum Befund
      formatter: date
    - original_name: V|1|ACMG Classification
      formatter: string
    - original_name: V|1|Genename
      formatter: string
    - original_name: V|1|Mutation
      formatter: string
    - original_name: V|1|Zygosity
      formatter: string
    - original_name: V|2|Genename
      formatter: string
    - original_name: V|2|Mutation
      formatter: string
    - original_name: V|3|Mutation
      formatter: string
    - original_name: TE an Frau Otto
      formatter: string
